osscameroon/osscameroon-website

frontend/src/containers/home.tsx

Fixes #154 
- Update query for fetching tweets and projects data on home page

enh(ui): add loader on top tweets and top projects

---

frontend/src/components/common/Breadcrumb.tsx
frontend/src/components/common/Project.tsx
frontend/src/components/common/Tweet.tsx
frontend/src/components/layout/footer.tsx
frontend/src/components/layout/header.tsx
frontend/src/components/utils/DarkModeBtn.tsx
frontend/src/components/utils/activeLink.tsx
frontend/src/styles/common.scss
frontend/src/styles/developers.scss
frontend/src/styles/footer.scss
frontend/src/styles/header.scss
frontend/src/styles/home.scss
frontend/src/styles/index.scss
frontend/src/styles/projects.scss

Dark mode for OSSCaroon Website. In case theme has not yet been set by user the browser theme ill be used.

Updated some styles to support dark mode

---

frontend/src/services/developers.ts

Displays 21 users per page as the developers' page has a 3x7 grid.

display 21 users per page instead of the default #157

---

frontend/src/components/layout/header.tsx
frontend/src/locales/messages.ts

Link to blog.osscameroon.com added to the header

link to blog.osscameroon.com added

---

scraper/github/app/cli.py
scraper/github/app/scrape_projects.py
scraper/github/app/scrape_users.py
scraper/github/app/utils/github_requests.py
scraper/github/tests/test_github_requests.py

Bon j'ai effectué quelques modifications:
- creation d'une classe client pour l'api github
- ajout des types
- augmentation de la vitesse d'execution du scraper
- ajout d'un algorithme pour recuperer plus de 1000 users

enhanced the scraper

---

frontend/src/containers/developers.tsx
frontend/src/containers/projects.tsx

in this issue the resolve bug on the developers and the projects pages by allowing the submission of the form by pressing Enter on the keyboard
Issue #165 and #164

for the issue #164 and #165

---

frontend/src/containers/home.tsx

fix the bug on the home page's search form.
The form can now be submitted by pressing the enter button on the  keyboard.

feat: fix the bug on the home page's search button

---

bots/hermes/Discription.txt
bots/hermes/bot.py

This is a telegram bot that will help to sort projects in the osscameroon and give recommendations  every week on the various osscameroon platforms such as telegram

feat: add hermes bot

---

frontend/public/index.html

Adding more meta-tag on the WebSite for the SEO.

feat(frontend): adding meta-tags for the SEO

---

frontend/src/components/common/Project.tsx
frontend/src/components/common/developer/Developer.tsx
frontend/src/components/common/developer/DeveloperItemLink.tsx
frontend/src/components/utils/absoluteLink.ts
frontend/src/containers/home.tsx
frontend/src/containers/projects.tsx
frontend/src/styles/developers.scss
frontend/src/utils/types.ts

This pull request is related to #176, #160, #169, #129

Add frontend project issues

---

frontend/src/components/layout/footer.tsx
frontend/src/components/layout/header.tsx
frontend/src/locales/messages.ts

and this pull request is linked to # 201

feat: add link miniyotas to headers and footer

---

frontend/src/containers/home.tsx
frontend/src/locales/fr.json
frontend/src/locales/messages.ts

This pull request add the open collective donation button on the website home page.

feat: add open collective donation button

---

frontend/src/components/common/ItemSortMethod.tsx
frontend/src/styles/index.scss

and this pull request is linked to #184 
/developers
/projets

fix(ui): Sort By dropdown background color on dark mode

---

frontend/src/components/common/Project.tsx
frontend/src/containers/home.tsx
frontend/src/styles/projects.scss

This pull request Fixes responsive issue on osscameroon cards and is linked to issue #202

fix: Home page Top projects card ui

---

api/README.md
api/requirements.txt

fix: fix dependencies + readme

---

frontend/src/containers/developers.tsx
frontend/src/containers/projects.tsx

fix(ui): Return to the top when browsing the pagination

---

frontend/src/components/common/Project.tsx

bug: Project card should not be centered

---

.gitignore
bots/hermes/Makefile
bots/hermes/cron_script.py
bots/hermes/requirements.txt

We would like the bot `hermes` to send messages to twitter

feat: send message to twitter

---

frontend/Dockerfile
frontend/README.md

- update README
- update the dockerfile node version

fix: docker node version

---

frontend/src/components/common/Project.tsx
frontend/src/containers/home.tsx
frontend/src/locales/en.json
frontend/src/locales/fr.json
frontend/src/locales/messages.ts
frontend/src/services/projects.ts

I think we should more share what we're working on and what we're doing on our website
This is my small contribution to that as a backendDev
⚠️ THis Pull Request depends on this one : https://github.com/osscameroon/project-ideas/pull/32

feat: add our project to the front-view

---

.github/dependabot.yml

- chore: added the dependabot integration for our deps
- chore: added more rules for scrapper and bots

chore: dependabot integration for our api, scrapper, bots and frontend

---

.github/dependabot.yml

- shorten the notification for the frontend from daily to weekly

feat: shorten notifications for the frontend

---

frontend/.env.example
frontend/README.md
frontend/jest.config.js
frontend/package.json
frontend/src/components/layout/footer.tsx
frontend/src/locales/messages.ts

https://user-images.githubusercontent.com/34966088/209425793-c1f88889-ee1a-4185-8d25-6ec59ce72fb5.mp4

Change link twitter
